{
	"request":{
		"additional_services":[
			"origin_condition_check"
		],
			"currency":"USD",
			"destination":{
			"access_restrictions":[
				"stairs_only"
			],
				"address_line_1":"",
				"address_line_2":"",
				"address_line_3":"",
				"city":"",
				"region":"",
				"postal_code":"",
				"country":"",
				"title":"",
				"contacts":[
				{
					"name":"",
					"email_address":"",
					"phone_number":""
				}
			]
		},
		"insurance":"arta_transit_insurance",
			"internal_reference":"",
			"objects":[

			],
			"origin":{
			"access_restrictions":[
				"non_paved"
			],
				"address_line_1":"",
				"address_line_2":"",
				"address_line_3":"",
				"city":"",
				"region":"",
				"postal_code":"",
				"country":"",
				"title":"",
				"contacts":[
				{
					"name":"",
					"email_address":"",
					"phone_number":""
				}
			]
		},
		"preferred_quote_types":[
			"parcel"
		],
			"public_reference":"",
			"shipping_notes":""
	}
}